language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x (x = 6 right now)
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86_64-google_apis-25